/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Feature = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const RestaurantInfo = IDL.Record({
  'hours' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getFeatures' : IDL.Func([], [IDL.Vec(Feature)], ['query']),
  'getMenuCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Feature = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const RestaurantInfo = IDL.Record({
    'hours' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getFeatures' : IDL.Func([], [IDL.Vec(Feature)], ['query']),
    'getMenuCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };